/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro.org.openapitools.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Call extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2931816696797468431L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Call\",\"namespace\":\"avro.org.openapitools.model\",\"fields\":[{\"name\":\"calledNumber\",\"type\":\"string\"},{\"name\":\"callerNumber\",\"type\":\"string\"},{\"name\":\"engagementDialogId\",\"type\":\"string\"},{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"participant\",\"type\":{\"type\":\"record\",\"name\":\"Participant\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"}]}},{\"name\":\"timestamp\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.DateConversion());
  }

  private static final BinaryMessageEncoder<Call> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Call> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Call> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Call> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Call> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Call to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Call from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Call instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Call fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence calledNumber;
  private java.lang.CharSequence callerNumber;
  private java.lang.CharSequence engagementDialogId;
  private java.lang.CharSequence id;
  private avro.org.openapitools.model.Participant participant;
  private java.time.LocalDate timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Call() {}

  /**
   * All-args constructor.
   * @param calledNumber The new value for calledNumber
   * @param callerNumber The new value for callerNumber
   * @param engagementDialogId The new value for engagementDialogId
   * @param id The new value for id
   * @param participant The new value for participant
   * @param timestamp The new value for timestamp
   */
  public Call(java.lang.CharSequence calledNumber, java.lang.CharSequence callerNumber, java.lang.CharSequence engagementDialogId, java.lang.CharSequence id, avro.org.openapitools.model.Participant participant, java.time.LocalDate timestamp) {
    this.calledNumber = calledNumber;
    this.callerNumber = callerNumber;
    this.engagementDialogId = engagementDialogId;
    this.id = id;
    this.participant = participant;
    this.timestamp = timestamp;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return calledNumber;
    case 1: return callerNumber;
    case 2: return engagementDialogId;
    case 3: return id;
    case 4: return participant;
    case 5: return timestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.DateConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: calledNumber = (java.lang.CharSequence)value$; break;
    case 1: callerNumber = (java.lang.CharSequence)value$; break;
    case 2: engagementDialogId = (java.lang.CharSequence)value$; break;
    case 3: id = (java.lang.CharSequence)value$; break;
    case 4: participant = (avro.org.openapitools.model.Participant)value$; break;
    case 5: timestamp = (java.time.LocalDate)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'calledNumber' field.
   * @return The value of the 'calledNumber' field.
   */
  public java.lang.CharSequence getCalledNumber() {
    return calledNumber;
  }


  /**
   * Sets the value of the 'calledNumber' field.
   * @param value the value to set.
   */
  public void setCalledNumber(java.lang.CharSequence value) {
    this.calledNumber = value;
  }

  /**
   * Gets the value of the 'callerNumber' field.
   * @return The value of the 'callerNumber' field.
   */
  public java.lang.CharSequence getCallerNumber() {
    return callerNumber;
  }


  /**
   * Sets the value of the 'callerNumber' field.
   * @param value the value to set.
   */
  public void setCallerNumber(java.lang.CharSequence value) {
    this.callerNumber = value;
  }

  /**
   * Gets the value of the 'engagementDialogId' field.
   * @return The value of the 'engagementDialogId' field.
   */
  public java.lang.CharSequence getEngagementDialogId() {
    return engagementDialogId;
  }


  /**
   * Sets the value of the 'engagementDialogId' field.
   * @param value the value to set.
   */
  public void setEngagementDialogId(java.lang.CharSequence value) {
    this.engagementDialogId = value;
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'participant' field.
   * @return The value of the 'participant' field.
   */
  public avro.org.openapitools.model.Participant getParticipant() {
    return participant;
  }


  /**
   * Sets the value of the 'participant' field.
   * @param value the value to set.
   */
  public void setParticipant(avro.org.openapitools.model.Participant value) {
    this.participant = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.time.LocalDate getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.time.LocalDate value) {
    this.timestamp = value;
  }

  /**
   * Creates a new Call RecordBuilder.
   * @return A new Call RecordBuilder
   */
  public static avro.org.openapitools.model.Call.Builder newBuilder() {
    return new avro.org.openapitools.model.Call.Builder();
  }

  /**
   * Creates a new Call RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Call RecordBuilder
   */
  public static avro.org.openapitools.model.Call.Builder newBuilder(avro.org.openapitools.model.Call.Builder other) {
    if (other == null) {
      return new avro.org.openapitools.model.Call.Builder();
    } else {
      return new avro.org.openapitools.model.Call.Builder(other);
    }
  }

  /**
   * Creates a new Call RecordBuilder by copying an existing Call instance.
   * @param other The existing instance to copy.
   * @return A new Call RecordBuilder
   */
  public static avro.org.openapitools.model.Call.Builder newBuilder(avro.org.openapitools.model.Call other) {
    if (other == null) {
      return new avro.org.openapitools.model.Call.Builder();
    } else {
      return new avro.org.openapitools.model.Call.Builder(other);
    }
  }

  /**
   * RecordBuilder for Call instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Call>
    implements org.apache.avro.data.RecordBuilder<Call> {

    private java.lang.CharSequence calledNumber;
    private java.lang.CharSequence callerNumber;
    private java.lang.CharSequence engagementDialogId;
    private java.lang.CharSequence id;
    private avro.org.openapitools.model.Participant participant;
    private avro.org.openapitools.model.Participant.Builder participantBuilder;
    private java.time.LocalDate timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(avro.org.openapitools.model.Call.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.calledNumber)) {
        this.calledNumber = data().deepCopy(fields()[0].schema(), other.calledNumber);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.callerNumber)) {
        this.callerNumber = data().deepCopy(fields()[1].schema(), other.callerNumber);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.engagementDialogId)) {
        this.engagementDialogId = data().deepCopy(fields()[2].schema(), other.engagementDialogId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.id)) {
        this.id = data().deepCopy(fields()[3].schema(), other.id);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.participant)) {
        this.participant = data().deepCopy(fields()[4].schema(), other.participant);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (other.hasParticipantBuilder()) {
        this.participantBuilder = avro.org.openapitools.model.Participant.newBuilder(other.getParticipantBuilder());
      }
      if (isValidValue(fields()[5], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[5].schema(), other.timestamp);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing Call instance
     * @param other The existing instance to copy.
     */
    private Builder(avro.org.openapitools.model.Call other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.calledNumber)) {
        this.calledNumber = data().deepCopy(fields()[0].schema(), other.calledNumber);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.callerNumber)) {
        this.callerNumber = data().deepCopy(fields()[1].schema(), other.callerNumber);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.engagementDialogId)) {
        this.engagementDialogId = data().deepCopy(fields()[2].schema(), other.engagementDialogId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.id)) {
        this.id = data().deepCopy(fields()[3].schema(), other.id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.participant)) {
        this.participant = data().deepCopy(fields()[4].schema(), other.participant);
        fieldSetFlags()[4] = true;
      }
      this.participantBuilder = null;
      if (isValidValue(fields()[5], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[5].schema(), other.timestamp);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'calledNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getCalledNumber() {
      return calledNumber;
    }


    /**
      * Sets the value of the 'calledNumber' field.
      * @param value The value of 'calledNumber'.
      * @return This builder.
      */
    public avro.org.openapitools.model.Call.Builder setCalledNumber(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.calledNumber = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'calledNumber' field has been set.
      * @return True if the 'calledNumber' field has been set, false otherwise.
      */
    public boolean hasCalledNumber() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'calledNumber' field.
      * @return This builder.
      */
    public avro.org.openapitools.model.Call.Builder clearCalledNumber() {
      calledNumber = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'callerNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getCallerNumber() {
      return callerNumber;
    }


    /**
      * Sets the value of the 'callerNumber' field.
      * @param value The value of 'callerNumber'.
      * @return This builder.
      */
    public avro.org.openapitools.model.Call.Builder setCallerNumber(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.callerNumber = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'callerNumber' field has been set.
      * @return True if the 'callerNumber' field has been set, false otherwise.
      */
    public boolean hasCallerNumber() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'callerNumber' field.
      * @return This builder.
      */
    public avro.org.openapitools.model.Call.Builder clearCallerNumber() {
      callerNumber = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'engagementDialogId' field.
      * @return The value.
      */
    public java.lang.CharSequence getEngagementDialogId() {
      return engagementDialogId;
    }


    /**
      * Sets the value of the 'engagementDialogId' field.
      * @param value The value of 'engagementDialogId'.
      * @return This builder.
      */
    public avro.org.openapitools.model.Call.Builder setEngagementDialogId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.engagementDialogId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'engagementDialogId' field has been set.
      * @return True if the 'engagementDialogId' field has been set, false otherwise.
      */
    public boolean hasEngagementDialogId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'engagementDialogId' field.
      * @return This builder.
      */
    public avro.org.openapitools.model.Call.Builder clearEngagementDialogId() {
      engagementDialogId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public avro.org.openapitools.model.Call.Builder setId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.id = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public avro.org.openapitools.model.Call.Builder clearId() {
      id = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'participant' field.
      * @return The value.
      */
    public avro.org.openapitools.model.Participant getParticipant() {
      return participant;
    }


    /**
      * Sets the value of the 'participant' field.
      * @param value The value of 'participant'.
      * @return This builder.
      */
    public avro.org.openapitools.model.Call.Builder setParticipant(avro.org.openapitools.model.Participant value) {
      validate(fields()[4], value);
      this.participantBuilder = null;
      this.participant = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'participant' field has been set.
      * @return True if the 'participant' field has been set, false otherwise.
      */
    public boolean hasParticipant() {
      return fieldSetFlags()[4];
    }

    /**
     * Gets the Builder instance for the 'participant' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public avro.org.openapitools.model.Participant.Builder getParticipantBuilder() {
      if (participantBuilder == null) {
        if (hasParticipant()) {
          setParticipantBuilder(avro.org.openapitools.model.Participant.newBuilder(participant));
        } else {
          setParticipantBuilder(avro.org.openapitools.model.Participant.newBuilder());
        }
      }
      return participantBuilder;
    }

    /**
     * Sets the Builder instance for the 'participant' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public avro.org.openapitools.model.Call.Builder setParticipantBuilder(avro.org.openapitools.model.Participant.Builder value) {
      clearParticipant();
      participantBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'participant' field has an active Builder instance
     * @return True if the 'participant' field has an active Builder instance
     */
    public boolean hasParticipantBuilder() {
      return participantBuilder != null;
    }

    /**
      * Clears the value of the 'participant' field.
      * @return This builder.
      */
    public avro.org.openapitools.model.Call.Builder clearParticipant() {
      participant = null;
      participantBuilder = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.time.LocalDate getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public avro.org.openapitools.model.Call.Builder setTimestamp(java.time.LocalDate value) {
      validate(fields()[5], value);
      this.timestamp = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public avro.org.openapitools.model.Call.Builder clearTimestamp() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Call build() {
      try {
        Call record = new Call();
        record.calledNumber = fieldSetFlags()[0] ? this.calledNumber : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.callerNumber = fieldSetFlags()[1] ? this.callerNumber : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.engagementDialogId = fieldSetFlags()[2] ? this.engagementDialogId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.id = fieldSetFlags()[3] ? this.id : (java.lang.CharSequence) defaultValue(fields()[3]);
        if (participantBuilder != null) {
          try {
            record.participant = this.participantBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("participant"));
            throw e;
          }
        } else {
          record.participant = fieldSetFlags()[4] ? this.participant : (avro.org.openapitools.model.Participant) defaultValue(fields()[4]);
        }
        record.timestamp = fieldSetFlags()[5] ? this.timestamp : (java.time.LocalDate) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Call>
    WRITER$ = (org.apache.avro.io.DatumWriter<Call>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Call>
    READER$ = (org.apache.avro.io.DatumReader<Call>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










