name: Deploy Project

on:
  repository_dispatch:
    types: [deploy-project]
    inputs:
      run_deploy:
        description: 'Run deployment step'
        required: true
        default: 'false'
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.run_deploy == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifacts
#        uses: actions/download-artifact@v4
#        with:
#          name: sam-artifacts
#      - run: ls -lR .aws-sam
        run: sam --version
